__numpy__

In [6]:
import numpy            #importing numpy module

In [7]:
import numpy as np      #importing numpy module using alias name np

__creation__

+   1 dimensional Numpy array
+   np.array(list)
+ 	n-dimensioanl Numpy array
+ 	This case – 1 dimensional
+	Homogeneous
+	Numpy – tries to convert all the elements into a single data type.

    +	E.g. if there is one element of type character, all the other elements will be converted to that type i.e. converts to the highest available data type

#### creating 1 dia array

In [8]:
lst1=[12,213,4345,56,8,89,45,67,55,123,25,32]
print(lst1)
type(lst1)

[12, 213, 4345, 56, 8, 89, 45, 67, 55, 123, 25, 32]


list

In [9]:
arr1=np.array(lst1)
print(arr1)
type(arr1)                             #output as list

[  12  213 4345   56    8   89   45   67   55  123   25   32]


numpy.ndarray

In [10]:
lst2=[12,213,4345,56,8,89,45,67,55,123,25,32,120.25]
arr2=np.array(lst2)
print(arr2)         #output as float because of there is any highest datatype then numpy return result as biggest datatype

[  12.    213.   4345.     56.      8.     89.     45.     67.     55.
  123.     25.     32.    120.25]


In [11]:
lst3=[12,213,4345,56,8,89,45,67,55,123,25,32,'abcd']
arr3=np.array(lst3)
print(arr3)                 #output as string

['12' '213' '4345' '56' '8' '89' '45' '67' '55' '123' '25' '32' 'abcd']


__extraction__

+ same as list and tuple

In [12]:
lst4=[12,213,4345,56,8,89,45,67,55,123,25,32]
arr4=np.array(lst4)
arr4[2]                            


4345

__manipulation (mutability)__

In [13]:
lst5=[12,213,4345,56,8,89,45,67,55,123,25,32]
arr5=np.array(lst5)
arr5[2]=arr5[2]*2
print(arr5)

[  12  213 8690   56    8   89   45   67   55  123   25   32]


__list vs numpy__

In [14]:
lst1=[12, 34, 67, 76, 44, 78, 90, 8, 23, 34, 56, 85,78,56,221]
print(lst1)

[12, 34, 67, 76, 44, 78, 90, 8, 23, 34, 56, 85, 78, 56, 221]


#### Extracting values based on a condition {values between 30 and 70}

In [15]:
lst2=[]
for i in lst1:
    if i>30 and i<70:
        lst2.append(i)
print(lst2)

[34, 67, 44, 34, 56, 56]


In [16]:
lst1=[12, 34, 67, 76, 44, 78, 90, 8, 23, 34, 56, 85,78,56,221]
arr1=np.array(lst1)
print(arr1)
type(arr1)

[ 12  34  67  76  44  78  90   8  23  34  56  85  78  56 221]


numpy.ndarray

In [17]:
# How conditional extraction works

arr1>30 # Provide contion --> Boolean output

array([False,  True,  True,  True,  True,  True,  True, False, False,
        True,  True,  True,  True,  True,  True])

In [18]:
arr1[arr1>30]

array([ 34,  67,  76,  44,  78,  90,  34,  56,  85,  78,  56, 221])

In [19]:
arr2=arr1[(arr1>30) & (arr1<70)]               #&,|,~
arr2
#print(arr2)

array([34, 67, 44, 34, 56, 56])

In [20]:
list(arr2)             #convert array into list

[34, 67, 44, 34, 56, 56]

In [21]:
lst2=[]
for i in lst1:
    if i>30 and i<70:
        lst2.append(i)
    final=np.array(lst2)
final

array([34, 67, 44, 34, 56, 56])

#### pos,neg and zero

In [22]:
lst4 = [-1,1,0,0,1,-1,0,1,1,-1,-1,1,0,1]
value_status=[]
for i in lst4:
    if i>0:
        value_status.append('pos')
    elif i<0:
        value_status.append('neg')
    else:
        value_status.append('zero')
print(value_status)

['neg', 'pos', 'zero', 'zero', 'pos', 'neg', 'zero', 'pos', 'pos', 'neg', 'neg', 'pos', 'zero', 'pos']


In [23]:
lst4 = [-1,1,0,0,1,-1,0,1,1,-1,-1,1,0,1]
print(lst4)
value_status=[]
for i in lst4:
    if i>0:
        value_status.append('pos')
    elif i<0:
        value_status.append('neg')
    else:
        value_status.append('zero')
print(value_status)

[-1, 1, 0, 0, 1, -1, 0, 1, 1, -1, -1, 1, 0, 1]
['neg', 'pos', 'zero', 'zero', 'pos', 'neg', 'zero', 'pos', 'pos', 'neg', 'neg', 'pos', 'zero', 'pos']


In [24]:
lst4 = [-1,1,0,0,1,-1,0,1,1,-1,-1,1,0,1]
arr4=np.array(lst4)
arr4

array([-1,  1,  0,  0,  1, -1,  0,  1,  1, -1, -1,  1,  0,  1])

In [25]:
value_status1=np.where(arr4>0,"Pos",
         np.where(arr4<0,"Neg","Zero"))
print(value_status1)

['Neg' 'Pos' 'Zero' 'Zero' 'Pos' 'Neg' 'Zero' 'Pos' 'Pos' 'Neg' 'Neg'
 'Pos' 'Zero' 'Pos']


In [26]:
print(list(value_status))

['neg', 'pos', 'zero', 'zero', 'pos', 'neg', 'zero', 'pos', 'pos', 'neg', 'neg', 'pos', 'zero', 'pos']


### 3.5 .arange

In [29]:


rg_1 = list(range(0,11,1))
rg_1



[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [30]:
rg_2 = np.arange(0,1.1,0.1)
rg_2

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

#### multi d array

In [31]:
lst2

[34, 67, 44, 34, 56, 56]

In [32]:
lst3


[12, 213, 4345, 56, 8, 89, 45, 67, 55, 123, 25, 32, 'abcd']

In [34]:
lst1

[12, 34, 67, 76, 44, 78, 90, 8, 23, 34, 56, 85, 78, 56, 221]

In [37]:
t1=(34, 67, 44, 34, 56, 56)
l1=[12, 213, 4345, 56, 8, 89, 45, 67]
l2=[8, 23, 34, 56, 85, 78, 56, 221]
print(t1,l1,l2)

(34, 67, 44, 34, 56, 56) [12, 213, 4345, 56, 8, 89, 45, 67] [8, 23, 34, 56, 85, 78, 56, 221]


In [43]:
mul_arr=np.array([(34, 67, 44, 34, 56, 56), [12, 213, 4345, 56, 8, 89], [8, 23, 34, 56, 85, 78]])

In [44]:
mul_arr

array([[  34,   67,   44,   34,   56,   56],
       [  12,  213, 4345,   56,    8,   89],
       [   8,   23,   34,   56,   85,   78]])

In [45]:
type(mul_arr)

numpy.ndarray