__numpy module__
   + Numerical python(numpy)
         

**import numpy**

In [1]:
import numpy as np

In [2]:
l1 = [12,34,67,76,44,78,90,8,23,34,56,85,989.8765]

In [3]:
arr1=np.array(l1)

In [4]:
print(arr1)             #1-D array

[ 12.      34.      67.      76.      44.      78.      90.       8.
  23.      34.      56.      85.     989.8765]


In [12]:
print(type(arr1))
print(arr1.ndim)   #define the diamension of array

<class 'numpy.ndarray'>
1


In [8]:
l1=[1,2,3,4,5]
l2=[6,7,8,9,10]

In [20]:
arr2=np.array([l1,l2])

In [21]:
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [24]:
arr2.ndim

2

In [29]:
arr2.shape    #print no of rows and no of columns

(2, 5)

In [30]:
sum(arr2)    #columnwise sum

array([ 7,  9, 11, 13, 15])

In [31]:
arr2.sum()    #sum of all elements in array

55

**Extraction**

In [34]:
l2 = [12,34,67,76,44,78,90,8,23,34,56,85]
arr=np.array(l2)

In [35]:
arr[1:10:2]

array([34, 76, 78,  8, 34])

In [37]:
arr4=arr*2   #mulyiply by 2 

In [38]:
print(arr4)

[ 24  68 134 152  88 156 180  16  46  68 112 170]


__extraction based on some conditions__

In [39]:
l2

[12, 34, 67, 76, 44, 78, 90, 8, 23, 34, 56, 85]

In [40]:
l2_edited = []
for i in l2:
    if i>30 and i<70:
        l2_edited.append(i)

In [41]:
print(l2_edited)

[34, 67, 44, 34, 56]


In [43]:
arr5=np.array(l2)

 How conditional extraction works

 Provide contion --> Boolean output

In [47]:
arr5>30        #result in bollean output

array([False,  True,  True,  True,  True,  True,  True, False, False,
        True,  True,  True])

 Provide condition inside a square bracket []

In [48]:
arr5[arr5>30]    #result in integer or same element 

array([34, 67, 76, 44, 78, 90, 34, 56, 85])

__Identify the positive, negative and zero__

__list__

In [49]:
l4 = [-1,1,0,0,1,-1,0,1,1,-1,-1,1,0,1]     

In [53]:
l44=[]
for i in l4:
    if i>0:
        l44.append('Pos')
    elif i<0:
        l44.append('Neg')
    else:
        l44.append('Zero')

In [54]:
print(l44)

['Neg', 'Pos', 'Zero', 'Zero', 'Pos', 'Neg', 'Zero', 'Pos', 'Pos', 'Neg', 'Neg', 'Pos', 'Zero', 'Pos']


__Array__

In [56]:
l4 = [-1,1,0,0,1,-1,0,1,1,-1,-1,1,0,1]
arr6=np.array(l4)

In [57]:
l44=np.where(arr6>0,"Pos",
         np.where(arr6<0,"Neg","Zero"))

In [58]:
print(l44)

['Neg' 'Pos' 'Zero' 'Zero' 'Pos' 'Neg' 'Zero' 'Pos' 'Pos' 'Neg' 'Neg'
 'Pos' 'Zero' 'Pos']
